Add Properties To Optimize The WASM binary Size per default
extism/dotnet-pdk pull request #61
Opened 2024-02-08 10:17 UTC by furesoft

I've done a research and figured out a custom msbuild sdk would be for this purpose an overkill so I added the specific properties to the nuget package. I also added the RuntimeIdentifier to automaticly use the right runtime.

2024-02-08 10:27 UTC, furesoft commented
One thing has to be done. The props file has to be included in the resulting nuget package with a nuspec file

2024-02-08 10:27 UTC, mhmd-azeez commented
Helo @furesoft thank you very much for the PR, looks good from a first look. I will do some tests and merge it

2024-02-13 15:36 UTC, mhmd-azeez commented
@furesoft I think if you put your changes into https://github.com/extism/dotnet-pdk/blob/main/src/Extism.Pdk/build/Extism.Pdk.targets It should work without needing a nuspec

2024-02-16 09:14 UTC, furesoft commented
> @furesoft I think if you put your changes into https://github.com/extism/dotnet-pdk/blob/main/src/Extism.Pdk/build/Extism.Pdk.targets It should work without needing a nuspec

I did, so it's ready to be merged

2024-02-17 17:55 UTC, mhmd-azeez requested changes

2024-02-17 17:55 UTC, mhmd-azeez commented on src/Extism.Pdk/build/Extism.Pdk.targets
> +		<RuntimeIdentifier>wasi-wasm</RuntimeIdentifier>
I think these have to be inside <PropertyGroup>

2024-02-18 08:51 UTC, mhmd-azeez commented
@furesoft thank you very much for the PR

2024-02-18 08:51 UTC, mhmd-azeez approved these changes

2024-02-18 08:51 UTC, merged